image:
  repository: b4bz/homer
  tag: latest
  pullPolicy: IfNotPresent

service:
  main:
    ports:
      http:
        port: 8080

ingress:
  main:
    enabled: true

probes:
  liveness:
    enabled: true
  readiness:
    enabled: true
  startup:
    enabled: true

persistence:
  config:
    enabled: true
    type: pvc
    accessMode: ReadWriteOnce
    size: 1Gi

addons:
  litestream:
    enabled: true
    volumeMounts:
      - name: config
        mountPath: /config
        readOnly: true
    dbs:
      - path: /config/db.sqlite3
        replicas:
          - url: s3://YOURBUCKET/db